#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->setName('Schema Diff');
$app->setVersion('1.0.0');
$app->add(new \Phlib\SchemaDiff\SchemaDiffCommand());
$app->setDefaultCommand('schemadiff', true);
$app->run();
