#!/usr/bin/env php
<?php
declare(strict_types=1);

// autoload
$autoloadFiles = [__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'];
foreach ($autoloadFiles as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        require_once $autoloadFile;
        break;
    }
}

use Symfony\Component\Console\Application;

$app = new Application();
$app->setName('Schema Diff');
$app->setVersion('1.1.0');
$app->add(new \Phlib\SchemaDiff\SchemaDiffCommand());
$app->setDefaultCommand('schemadiff', true);
$app->run();
