name: CodeChecks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'

    name: PHP ${{ matrix.php }} tests

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: adminpass
      DB_DATABASE_1: test_database_1
      DB_DATABASE_2: test_database_2
      DB_ROOT_USERNAME: root
      DB_ROOT_PASSWORD: rootpass

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ env.DB_DATABASE_1 }}
          MYSQL_HOST: ${{ env.DB_HOST }}
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE_2 }};' -h${{ env.DB_HOST }} -u${{ env.DB_ROOT_USERNAME }} -p${{ env.DB_ROOT_PASSWORD }}
          mysql -e 'GRANT ALL PRIVILEGES ON ${{ env.DB_DATABASE_2 }}.* TO "${{ env.DB_USERNAME }}"@"%";' -h${{ env.DB_HOST }} -u${{ env.DB_ROOT_USERNAME }} -p${{ env.DB_ROOT_PASSWORD }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Composer
        run: composer install --no-progress

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        env:
          INTEGRATION_ENABLED: 1

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v2"
        with:
          fail_ci_if_error: true
